### ISSUE TITLE
Any experience with Helix editor and Rust development (LSP, debugging, etc)?

### ISSUE THREAD

**Issue by johnnyutahh** [rsdlt/nvim-config-files#5]
Great writeup here:

https://rsdlt.github.io/posts/rust-nvim-ide-guide-walkthrough-development-debug/

Any experience or thoughts about doing similar things with https://helix-editor.com ?

**Comment by rsdlt** [comment]
Hi @johnnyutahh, thanks for the kudos on the walkthrough. I've used Helix and in my opinion it is really good and convenient with very sane config from the get go. It took me a while to adapt the select-edit paradigm, but once I built muscle memory it became a very nice dev experience.

**Comment by johnnyutahh** [comment]
That's super helpful @rsdlt, thank you.

If it's not already happened, can you see a future where Helix might replace Neovim as your primary Rust-IDE (assuming Neovim is/was your primary IDE)?

_[Pls do not feel obligated to reply, I do not wish to annoy. You've already done such excellent work to help me "spin up" in this Rust-IDE world.]_

My background/context:

I'm a long-time Vim (non-Neovim) user looking to upgrade to a better development environment and I'm learning Rust. I plan to dabble in both Neovim (per your excellent, above walkthrough) and Helix to learn more. However, if I get the feeling that [Helix might be mature enough](https://www.reddit.com/r/neovim/comments/u7do3k/neovim_vs_helix_which_is_the_best_vivim_style/) to be my primary IDE platform I may initially focus on it (Helix). Alas, I get the sense it might take a while for Helix to "get there."

Additional comments welcome, but of course in no way required. I may start another Helix-vs-Neovim comparison discussion (like the one referenced above which is about a year old) if it's warranted I can't find more current info.

**Comment by johnnyutahh** [comment]
ps. Is there some way I can donate/contribute funds to you or your projects? (Apologies if I missed a donate/OpenColletive or some similar link.)

**Comment by rsdlt** [comment]
You're welcome! I do probably see a future when switching might happen. 

I haven't been able to setup the debugging experience on Helix yet; so if one day I get down on how to debug fast then I don't see why not switching: It's fast, works really well, the config is pretty straightforward, and its dev community seems pretty active. 

On my Windows laptop I currently have Helix as my default editor for Powershell, so that I get comfortable using it in editing all sorts of docs (and get used to switch form Vim-like editing to Hx-like editing). 

For some work-related stuff I use CLion with ideavim plugin, which also works extremely well, particularly for debugging. 

In any case, I think focusing on Helix to learn Rust is a solid choice.  You can run cargo via the `:sh cargo run/check/build` commands:

![image](https://user-images.githubusercontent.com/109830882/228324067-1676beb0-4171-420a-8231-a72697e0e892.png)

And also get linters / lens automatically which can help you in focusing on learning Rust:
![image](https://user-images.githubusercontent.com/109830882/228324715-f3e35a42-c5e5-468b-82b5-b5a0fae43bc4.png)

I might be wrong, but I believe the Helix devs use Helix itself to develop Helix... So that would be a testament on its robustness for developing large applications. 

Good luck in your Rust journey!

P.s. I haven't setup any donate button, but if you want to contribute you can donate via my PayPal link: [@rosantiago16](https://paypal.me/rosantiago16?country.x=US&locale.x=en_US)  That would be awesome and much appreciated! It would be the first donation I receive :)
